### ISSUE TITLE
请问论文中表Ⅶ的各算法在多模态下的数据结果您是如何实现的，因为我并没有找到公开的算法代码

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#101]

**Comment by leileilei2000** [comment]
如果可以的话，能否请您分享一份YOLOrs和YOLO Fusion的代码，我的邮箱是2303025778@qq.com

**Comment by icey-zhang** [comment]
我按照论文的结构复现的，这是YOLOrs的yaml文件

`#20210318 zjq
# parameters
nc: 8  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

#anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

steam:
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2
   [-1, 1, Bottleneck, [64]],
   [-1, 1, Conv, [32, 1, 1]],
  ]

backbone:
  #[from, number, module, args]
  [ 
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, 2, Bottleneck, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 5-P3/8
   [-1, 8, Bottleneck, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 7-P4/16
   [-1, 8, Bottleneck, [512]],
  ]

# YOLOv3 head
head:
  [ #[-1, 1, Bottleneck, [1024, False]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [512, 3, 1]],
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Conv, [512, 3, 1]], 
   [-1, 1, Conv, [14, 1, 1]], # (P4/128-large)

   [-2, 1, Conv, [128, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 3], 1, Concat, [1]],  # cat backbone P3 6
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, Conv, [256, 3, 1]],  
   [-1, 1, Conv, [14, 1, 1]], # (P4/64-medium)

   [-2, 1, Conv, [64, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [3, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, -2], 1, Concat, [1]],  # cat backbone P3 6
   [-1, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [64, 1, 1]],
   [-1, 1, Conv, [128, 3, 1]],
   [-1, 1, Conv, [14, 1, 1]],  # (P3/32 -small)

   [[33, 22, 12], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5) 27 22 15
  ]
`
