### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by keepfighting666** [icey-zhang/SuperYOLO#107]
我尝试了不同的numpy版本，1.24、1.20都不行，请问是需要修改代码吗

**Comment by jacksonwu09** [comment]
是的 直接使用int即可

**Comment by Czeni1** [comment]
> 是的 直接使用int即可

请问这个是什么意思呢 怎么修改这个问题呢

**Comment by jacksonwu09** [comment]
> > 是的 直接使用int即可
> 
> 请问这个是什么意思呢 怎么修改这个问题呢

你直接百度吧 这个百度有的

**Comment by Czeni1** [comment]
> > > 是的 直接使用int即可
> > 
> > 
> > 请问这个是什么意思呢 怎么修改这个问题呢
> 
> 你直接百度吧 这个百度有的

好滴好滴 已经解决了
