### ISSUE TITLE
test结果

### ISSUE THREAD

**Issue by jacksonwu09** [icey-zhang/SuperYOLO#109]
<img width="437" alt="image" src="https://github.com/icey-zhang/SuperYOLO/assets/69404310/9e21dcd0-e5d1-4e6e-b640-0666152b8e49">

为什么我的测试结果比你论文中的高5%，这样是正常的吗

**Comment by 972238672** [comment]
我使用了作者提供的预训练权重训练后最好的效果中MAP50达到了0.822

**Comment by jacksonwu09** [comment]
> 我使用了作者提供的预训练权重训练后最好的效果中MAP50达到了0.822
您好，我想问下，你就直接使用作者提供的代码，没有修改，使用作者提供的fold1权重运行后就0,822吗，你使用从头训练的权重的map50有多少

**Comment by 972238672** [comment]
很抱歉我没有从头训练过

**Comment by jacksonwu09** [comment]
你好，我想问下 这个mAP是仅在fold11上的吗，那如果比较的话，是与下图中哪个图进行比较
<img width="732" alt="image" src="https://github.com/icey-zhang/SuperYOLO/assets/69404310/68cc5350-f54b-44ae-b91c-e43e2b609d02">
<img width="743" alt="image" src="https://github.com/icey-zhang/SuperYOLO/assets/69404310/9453e431-ecf4-4141-95d1-f5d27055dcb4">

**Comment by farhaniqbalbajwa** [comment]
I think the results you provided are only of fold 1. but in paper he averaged the mAP of all 10 folds which is 75.09. 
mAP of fold1 is 80.9

**Comment by jacksonwu09** [comment]
> I think the results you provided are only of fold 1. but in paper he averaged the mAP of all 10 folds which is 75.09. mAP of fold1 is 80.9

Thank you for your answer, I have figured it out.
