### ISSUE TITLE
YOLOv5是什么版本？显存占用是多少？推理速度怎么样?

### ISSUE THREAD

**Issue by fcqfcq** [icey-zhang/SuperYOLO#11]

**Comment by icey-zhang** [comment]
感谢关注，YOLOv5是5.0的版本，针对小目标检测做了一些改进，显存占用没有仔细关注，用2080Ti单卡与1080Ti单卡都可完成测试，推理速度指标的对比可以参考GFLOPs指标的对比

**Comment by JusticeLin** [comment]
> 感谢关注，YOLOv5是5.0的版本，针对小目标检测做了一些改进，显存占用没有仔细关注，用2080Ti单卡与1080Ti单卡都可完成测试，推理速度指标的对比可以参考GFLOPs指标的对比

请问为什么superyolo推理速度很慢，要50多毫秒，但是v7 v8都很快，只要20多
