### ISSUE TITLE
测试使用作者提供的预训练权重问题

### ISSUE THREAD

**Issue by Czeni1** [icey-zhang/SuperYOLO#111]
我想问一下，这个预训练权重是使用下面图片中的哪一个呀
<img width="168" alt="ddeebfb54e9e0f73ace6c2d731610f8" src="https://github.com/icey-zhang/SuperYOLO/assets/152961525/69c341a3-332a-487f-8256-61fd44ca74c7">
我使用了第一个，但是测试结果显示都是0
![Uploading ab9ed7f2791eec168d8202b5569bcc0.png…]()
这是我用的测试命令
![Uploading a1762126416e4e665c1091abc2ea775.png…]()

**Comment by icey-zhang** [comment]
VEDAI数据集有10种划分方式，所以有10个权重，看你测哪个划分就用哪个，结果是0不太正常哦，用任意一个应该都是会有精度的。
