### ISSUE TITLE
请问作者在export过程中是否有遇到过索引越界问题，具体问题在commom.py的MF类中

### ISSUE THREAD

**Issue by Sparkle-knight** [icey-zhang/SuperYOLO#112]
<img width="802" alt="48069f71ba5c77cfa0d2cf743f4add9" src="https://github.com/icey-zhang/SuperYOLO/assets/134896542/b6dd4afc-1c35-42c5-abcd-09c24c73406b">

**Comment by icey-zhang** [comment]
可以发一下报错截图？
