### ISSUE TITLE
测试模型参数和GFLOPs问题

### ISSUE THREAD

**Issue by Czeni1** [icey-zhang/SuperYOLO#113]
作者，您好，我使用了SRyolo_MF作为配置文件，输入形式为RGB+IR+MF,训练和测试都是按照你的命令运行的，但为什么显示GFLOPs有56.9呢？我看您结果上只显示了是十几。
<img width="429" alt="3f4713a100251f53e18144732fc6b26" src="https://github.com/icey-zhang/SuperYOLO/assets/152961525/30ac06e3-cf63-4c41-b4e9-f7d0e4e3ca95">

**Comment by jacksonwu09** [comment]
你要在test.py中把那个参数部分的注释解开

**Comment by Czeni1** [comment]
> 你要在test.py中把那个参数部分的注释解开
好滴 出来结果了 我想请问一下你的btachsize设置的是多少呀？

**Comment by jacksonwu09** [comment]
> > 你要在test.py中把那个参数部分的注释解开
> > 好滴 出来结果了 我想请问一下你的btachsize设置的是多少呀？

我就按作者设置的啊，我设置为1或2结果没啥变化

**Comment by jacksonwu09** [comment]
对了，这个mAP是下面两幅图中那个结果啊
<img width="758" alt="image" src="https://github.com/icey-zhang/SuperYOLO/assets/69404310/a32eaa74-64d2-4c86-8d34-e77759f2fae3">
<img width="768" alt="image" src="https://github.com/icey-zhang/SuperYOLO/assets/69404310/fedc0974-a134-4d99-8c6f-ee9e13012e33">

**Comment by icey-zhang** [comment]
消融是在数据集fold1上做的，最后的结果是fold1-fold10的平均值，具体可看论文

**Comment by Thomas-403** [comment]
> 你要在test.py中把那个参数部分的注释解开

请问具体在哪呀
