### ISSUE TITLE
训练时无法找到标签

### ISSUE THREAD

**Issue by icey-zhang** [icey-zhang/SuperYOLO#116]
https://github.com/icey-zhang/SuperYOLO/issues/45

**Comment by wang-yt0801** [comment]
Perhaps I still have this issue while using it. Is the problem occurring in the data or within the program?

**Comment by Lucyhahahahha** [comment]
> Perhaps I still have this issue while using it. Is the problem occurring in the data or within the program?

Have u already solved this problem?
