### ISSUE TITLE
SR的效果如何体现

### ISSUE THREAD

**Issue by 972238672** [icey-zhang/SuperYOLO#120]
我在fold1上用train_image = 1024，noSR的效果总是比train_image = 1024,with SR的效果好上两个点，那么SR的作用体现在哪？

**Comment by icey-zhang** [comment]
1.这样的比较并不公平，train1024withSR输入检测网络的图像大小应该是512的大小，如果和1024直接输入网络，那确实会出现输入图像分辨率越高，检测效果越好的情况。
2.SR的作用包含，通过提高backbone细节特征提取能力提高低分图像的检测性能；通过低分输入降低网络计算量，实现加速；并且SR网络独立于检测网络可在测试阶段被移除从而不增加额外的参数量和计算量。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月17日 08:27 |
| 收件人 | icey-zhang/SuperYOLO ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [icey-zhang/SuperYOLO] SR的效果如何体现 (Issue #120) |

我在fold1上用train_image = 1024，noSR的效果总是比train_image = 1024,with SR的效果好上两个点，那么SR的作用体现在哪？

**Comment by 972238672** [comment]
我尝试过用训练imagesize=512，noSR,map50 = 69.2，使用imagesize=1024，withSR,map50 = 76.5这样差距会不会太大，另一个问题是，如果不用相同的imagesize，如何评价是SR带来的提升，还是单纯的提高了分辨率带来的提升？

**Comment by icey-zhang** [comment]
我们已经验证了VEDAI数据集1024双线性插值下采和512图像是一致的
