### ISSUE TITLE
SR网络

### ISSUE THREAD

**Issue by HoOoOY9** [icey-zhang/SuperYOLO#123]
您好！感谢您出色的工作！想请教您是否可以用别的SR网络替换当前的SR网络进行实验，以进一步提升检测性能呢？

**Comment by icey-zhang** [comment]
可以的

**Comment by HoOoOY9** [comment]
感谢您的回复。请问在.yaml文件中为什么没有SR网络的相关配置呢？修改的话是只需要在SRyolo.py的相应位置进行修改就可以了吗？
