### ISSUE TITLE
Tag corresponding category

### ISSUE THREAD

**Issue by qiherong** [icey-zhang/SuperYOLO#124]
May I ask what categories correspond to the tags 0-7 in sequence
请问下0-7的标签依次对应的类别是什么

**Comment by icey-zhang** [comment]
The dataset is here:VEDAIdataset.zip - Google 云端硬盘 <https://drive.google.com/file/d/1Fz0VVlBS924pM3RQvcTsD_qaGjxzIv3y/view>

**Comment by icey-zhang** [comment]
https://github.com/icey-zhang/SuperYOLO/blob/f6a59dc0fdecf04d5e28e1fcc9d878df9563f841/data/SRvedai.yaml#L23
