### ISSUE TITLE
SR分支

### ISSUE THREAD

**Issue by thestars-maker** [icey-zhang/SuperYOLO#125]
该网络架构是在yolov5上做了相关工作，在SRyolo_MF.yaml或其他yaml中哪里有体现SR工作呢，是怎样连接一个新分支在yolov5上的呢。求教，非常感谢

**Comment by icey-zhang** [comment]
https://github.com/icey-zhang/SuperYOLO/blob/f6a59dc0fdecf04d5e28e1fcc9d878df9563f841/models/SRyolo.py#L103
