### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by Pluviophile-sy** [icey-zhang/SuperYOLO#126]
Thanks for sharing the code.
I got the following error:
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

what is the best way to solve this problem should I change the environment? can any body give me the right environment versions for the libraries? or I should change the np.int. to np.int32 ?

_Originally posted by @Nadeen86 in https://github.com/icey-zhang/SuperYOLO/issues/118#issuecomment-2212386760_

**Comment by LennoxWei** [comment]
did you solve the problem? I came up with the same problem

**Comment by Pluviophile-sy** [comment]
> did you solve the problem? I came up with the same problem

Hi, this problem was solved by me at that time, but it has been half a year, and I have forgotten the specific solution. Maybe it is to change the data type of a parameter in numpy library, or to use another version of the library. You can try it, but I am not sure whether these methods are correct or not, I am sorry for not helping you
