### ISSUE TITLE
多模态数据集的制作

### ISSUE THREAD

**Issue by 624861627** [icey-zhang/SuperYOLO#129]
您好，我测试您所提出的模型，发现效果非常不错，我想将模型应用到自己的数据集中，但是暂时不太明白如何制作自己的多模态数据集，能提供相关的帮助吗？

**Comment by icey-zhang** [comment]
1.首先确认模态数量
2.本代码目前支持双模态数据集
3.多模态数据集存在对齐问题，需要特别注意，本论文中使用的VEDAI是对齐图像
4.制作数据集相关的可以看看会议论文中的dataset track的论文
