### ISSUE TITLE
Download via Baidu

### ISSUE THREAD

**Issue by cathkr7** [icey-zhang/SuperYOLO#13]
Thank you for releasing the code!

Results from the proposed method is quite impressive to me.

I tried to test the code with pretrained weights,

but the download link via Baidu is not possible for me(maybe because it's outside of china)

Is there any other way or link to download the pretrained weights?

Thank you,

**Comment by icey-zhang** [comment]
Sorry about our negligence, the weights are uploaded to google drive.
You can download them from the google driven link:

https://drive.google.com/drive/folders/1uLgWbNO_rSGLGa2yFS2Lm85gd1CqC_NM?usp=sharing

**Comment by cathkr7** [comment]
> Sorry about our negligence, the weights are uploaded to google drive. You can download them from the google drive link:
> 
> https://drive.google.com/drive/folders/1uLgWbNO_rSGLGa2yFS2Lm85gd1CqC_NM?usp=sharing

Thank you so much^^
