### ISSUE TITLE
对比模型是否进行图像下采样的问题

### ISSUE THREAD

**Issue by xf23210** [icey-zhang/SuperYOLO#137]
您好，您在文章中提到：“In order to realize the SR assisted branch, the input images of the network are downsampled from 1024 x 1024 size to 512 x 512 during the training process. In the test process, the image size is 512 x 512, which is consistent with the input of other algorithms compared.” 那么对于YOLOrs等对比方法，在训练阶段也是将1024 x 1024的图片下采样到512 x 512大小然后输入网络，在测试时直接使用数据集中的512 x 512图片吗？

**Comment by icey-zhang** [comment]
是的

**Comment by xf23210** [comment]
> 是的

非常感谢您的回复
