### ISSUE TITLE
数据集图像尺寸

### ISSUE THREAD

**Issue by gabaebae123** [icey-zhang/SuperYOLO#138]
请问如果训练自己的数据集，需要将图像resize成1024*1024或512*512吗？相应的labels标签呢？

**Comment by icey-zhang** [comment]
训练图像的不用处理，代码中有下采操作
标签的话，检测的标签是相对坐标位置，不需要更改，超分的标签需要使用原图（本论文中的1024）
验证或者测试需要使用下采好的图像（本论文中的512）并输入网络

具体可以看代码！
