### ISSUE TITLE
10-Fold data 

### ISSUE THREAD

**Issue by cathkr7** [icey-zhang/SuperYOLO#14]
Thank you for the google link of pretrained data.

I tested the pretrained data and have another question.

I downloaded the VEDAI dataset from the web site of "https://downloads.greyc.fr/vedai/"

because of the same link problem.

There are 10 fold related text files(fold01.txt~fold10.txt) in the folder of "Annotations512" from the web site.

Are those files same to the files of [baiduyun](your Baidu link)?

Thank you,

**Comment by icey-zhang** [comment]
We have completed some processes in the VEDAI dataset, and you can download the dataset used in our paper directly from the google drive link as follow:
https://drive.google.com/file/d/1Fz0VVlBS924pM3RQvcTsD_qaGjxzIv3y/view?usp=sharing
Then you can use the code https://github.com/icey-zhang/GHOST/blob/main/data/transform_vedai.py to change the path for yourself

**Comment by cathkr7** [comment]
> We have completed some processes in the VEDAI dataset, and you can download the dataset used in our paper directly from the google drive link as follow: https://drive.google.com/file/d/1Fz0VVlBS924pM3RQvcTsD_qaGjxzIv3y/view?usp=sharing Then you can use the code https://github.com/icey-zhang/GHOST/blob/main/data/transform_vedai.py to change the path for yourself.

Thank you for your kindness.
