### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Godk02** [icey-zhang/SuperYOLO#142]
大佬你好，我下载了你提供的VEDAI数据集，我只想用到可见光的数据集，我想在YOLOv8中跑，能直接删除红外的图像，其他的不改动吗

**Comment by Godk02** [comment]
另外我看了VEDAI数据集里分了十份，十折交叉验证请问是跑十次不同的取平均吗？

**Comment by icey-zhang** [comment]
1.可以的 2.消融实验是按fold1完成的，最后的与其他算法的对比是10个folds求平均

**Comment by icey-zhang** [comment]
1.迁移到v8，可以考虑单独将SR部分加到v8代码上 2.消融实验是按fold1完成的，最后的与其他算法的对比是10个folds求平均
