### ISSUE TITLE
损失函数的修改

### ISSUE THREAD

**Issue by 2029686068** [icey-zhang/SuperYOLO#143]
作者你好，感谢你的贡献，我想问下损失函数的修改在代码的哪部分可以找到

**Comment by 2029686068** [comment]
你好我仔细找了loss部分发现与v5原来的损失函数并无区别

**Comment by icey-zhang** [comment]
https://github.com/icey-zhang/SuperYOLO/blob/87b8557aea501855887f309653c4b64f0f1f6dc9/train.py#L404
