### ISSUE TITLE
在yolov8n上复现

### ISSUE THREAD

**Issue by haizi32** [icey-zhang/SuperYOLO#144]
作者您好，我尝试在yolov8n上复现论文的方法，发现加入SR分支监督后指标还有所下降(SR分支采用和您一样的EDSR，权重为0.1)，请问您有在yolov8n上进行过尝试吗

**Comment by icey-zhang** [comment]
你好，未在v8上尝试，但是可以考虑一下的一些问题


1.确认一下目标检测损失和超分损失两个要：目标检测损失>超分损失
2.你指的精度下降，是比较的2nx2n大小图像的yolov8n和nxn大小图像的yolov8n+SR么，这样的话精度是yolov8n(2nx2n)>yolov8n+SR(nxn)
3.可以考虑的调整参数：损失函数系数，检测网络的大小（因为SR的网络如果远远大于检测网络，会影响检测网络性能）

**Comment by haizi32** [comment]
> 你好，未在v8上尝试，但是可以考虑一下的一些问题
> 
> 1.确认一下目标检测损失和超分损失两个要：目标检测损失>超分损失 2.你指的精度下降，是比较的2nx2n大小图像的yolov8n和nxn大小图像的yolov8n+SR么，这样的话精度是yolov8n(2nx2n)>yolov8n+SR(nxn) 3.可以考虑的调整参数：损失函数系数，检测网络的大小（因为SR的网络如果远远大于检测网络，会影响检测网络性能）

您好 我的实验：1、实验是目标检测损失>超分损失    2、精度下降是yolov8n(nxn)>yolov8n+SR(nxn)   3、我看您论文里面的SR的网络是远大于检测网络的我就依据您代码复现了SR网络，实际也验证过目标检测网络的计算量和SR网络的计算量基本相同的情况下检测率也没有提升

**Comment by Yipzcc** [comment]
> > 你好，未在v8上尝试，但是可以考虑一下的一些问题
> > 1.确认一下目标检测损失和超分损失两个要：目标检测损失>超分损失 2.你指的精度下降，是比较的2nx2n大小图像的yolov8n和nxn大小图像的yolov8n+SR么，这样的话精度是yolov8n(2nx2n)>yolov8n+SR(nxn) 3.可以考虑的调整参数：损失函数系数，检测网络的大小（因为SR的网络如果远远大于检测网络，会影响检测网络性能）
> 
> 您好 我的实验：1、实验是目标检测损失>超分损失 2、精度下降是yolov8n(nxn)>yolov8n+SR(nxn) 3、我看您论文里面的SR的网络是远大于检测网络的我就依据您代码复现了SR网络，实际也验证过目标检测网络的计算量和SR网络的计算量基本相同的情况下检测率也没有提升

你好，请问可以交流一下吗？我是在v10n上面在自己的小目标数据集上加入了SR，也是yolo(nxn)>yolo+SR(nxn) ，EDSR，权重为0.1，验证集上AP50有提点，但是AP5095掉点了，测试集都掉点了
