### ISSUE TITLE
推理时找不到对应的数据集文件？

### ISSUE THREAD

**Issue by River-Cold** [icey-zhang/SuperYOLO#16]
您好，我在尝试使用small_EDSR_MF_fold1.pt预训练权重推理VEDAI测试集时发现并未找到对应的图片文件。报错截图如下：
![image](https://user-images.githubusercontent.com/80696033/220945684-8f069550-ebe1-4c9d-9bb7-5ed072cb2f87.png)
我使用了您提供的transform.py对数据集进行预处理，并按照自己的路径配置好了SRvedai.yaml，生成的fold01test_write.txt如下所示：
![image](https://user-images.githubusercontent.com/80696033/220945899-7c8d55da-f548-4b39-b54f-544e24c327da.png)
我猜测可能是fold01test_write.txt文件里的图片路径后缀不对造成的，但我仍然不知道该如何修改才能使数据集和图片对应上，烦请您帮忙指点一下啦3Q

**Comment by icey-zhang** [comment]
可以看一下你的SRvedai.yaml的配置文件吗？
建议从几个方面去确认
1.下载最新的code
2.确保 test.py 使用的是 from utils.datasets import  create_dataloader_sr 中的 create_dataloader_sr函数
3.删除cache缓存文件，单步调试到 https://github.com/icey-zhang/SuperYOLO/blob/main/utils/datasets.py 第684行 确认self.img_files路径是否正确
4.我这生成的cache文件是label.cache
5.因为我这这个代码按照这个步骤修改是可以跑起来的，不确定你是哪的问题，所以建议单步调试看看

**Comment by icey-zhang** [comment]
python train.py --cfg models/SRyolo_MF.yaml --super --train_img_size 1024 --hr_input --data data/SRvedai.yaml --ch 64 --input_mode RGB+IR+MF

若使用MF模块，需要将input_mode设置成RGB+IR+MF
