### ISSUE TITLE
关于不同训练模式下的配置修改和运行命令问题

### ISSUE THREAD

**Issue by foremistry** [icey-zhang/SuperYOLO#18]
您好！在readme文件中，是否可以较为详细的说明下RGB、IR、RGB+IR+MF、RGB+IR+fusion几种模式下，应该如何修改配置和运行命令？
另外，如果不使用超分辨率分支辅助训练的话，上述几种模式如何设置？谢谢！

**Comment by icey-zhang** [comment]
已更新
