### ISSUE TITLE
如何修改batch_size

### ISSUE THREAD

**Issue by roileaner** [icey-zhang/SuperYOLO#19]
张博士您好，代码中修改batch_size的地方应该在哪里，配置文件里面没有这一处
在运行代mf模块的train文件中报错ZeroDivisionError: float division by zero
![image](https://user-images.githubusercontent.com/93711597/225830922-6c7915fa-c6b9-44f1-92c0-baa8e3b1515a.png)
![image](https://user-images.githubusercontent.com/93711597/225831115-90966970-8d8c-47aa-aeb4-c18fced67a81.png)
这两个地方的代码怎么理解，ch_in传递变成了64-3-1

**Comment by icey-zhang** [comment]
修改batch size： https://github.com/icey-zhang/SuperYOLO/blob/c6aca72e303b429d257acf263dadeb872e866b33/train.py#L589
这个结构在论文终版中有提到，分别对应这张图上的三个seblock
https://github.com/icey-zhang/SuperYOLO/blob/main/Fig/Fusion_se.png
