### ISSUE TITLE
Option w.r.t '--multi-scale' 

### ISSUE THREAD

**Issue by cathkr7** [icey-zhang/SuperYOLO#20]
Is it possible to use --multi-scale option in training?

In my case, there is an error of "sr_loss = 0.1*(torch.nn.L1Loss()(ouput~~)" in the line 512 in train.py.

Could you help me in this case?

Thank you so much.

**Comment by icey-zhang** [comment]
In my experiments, I haven't used --multi-scale option in training. Could you describe your error in detail？ Let us solve it together.

**Comment by cathkr7** [comment]
> In my experiments, I haven't used --multi-scale option in training. Could you describe your error in detail？ Let us solve it together.

Thank you for your response!

Firstly, I will try to solve the problem of training with '--multi-scale' option by myself.

After that, if I need your help or opinion, I will revisit this site^^. 

Thank you so much!

**Comment by icey-zhang** [comment]
OK, and if you have any questions, I am glad to provide some help.
