### ISSUE TITLE
在训练的时候glops计算量不显示是怎么回事

### ISSUE THREAD

**Issue by zhangshoulong** [icey-zhang/SuperYOLO#22]
在训练的时候glops计算量不显示是怎么回事

**Comment by icey-zhang** [comment]
用test.py文件中的thop库可以测试参数量和GFLOPs。解开注释就可以。 
        # import thop
        # input_image_size = opt.img_size
        # input_image = torch.randn(1, 3, input_image_size, input_image_size).to(device)
        # flops, params = thop.profile(model, inputs=(input_image,input_image,input_mode), verbose=False)
        # print('Params: %.4fM'%(params/1e6))
        # print('FLOPs: %.2fG'%(flops/1e9))

**Comment by zhangshoulong** [comment]
感谢

**Comment by leileilei2000** [comment]
> 用 test.py 文件中的thop库可以测试参数量和GFLOPs。解开注释就可以。 # import thop # input_image_size = opt.img_size # input_image = torch.randn（1， 3， input_image_size， input_image_size）.to（device） # flops， params = thop.profile（model， inputs=（input_image，input_image，input_mode）， verbose=False） # print（'Params： %.4fM'%（params/1e6）） # print（'FLOPs： %.2fG'%（flops/1e9））

![Snipaste_2024-01-13_09-47-20](https://github.com/icey-zhang/SuperYOLO/assets/144891526/2de4d98c-8459-4465-b76a-35f303f87392)
为什么前后输出的参数不一样呢？
