### ISSUE TITLE
你好，项目中存在RuntimeError 这个错误 

### ISSUE THREAD

**Issue by zhangshoulong** [icey-zhang/SuperYOLO#24]
![image](https://user-images.githubusercontent.com/52525731/231062163-0b2e04e1-8c8e-4a02-aa7e-f6d6976bedf4.png)

**Comment by PrisonMike-Guy** [comment]
I have got the same problem

**Comment by PrisonMike-Guy** [comment]
@zhangshoulong I figured it out. 

In line 218 in loss.py
change 
`indices.append((b, a, gj.clamp_(0, gain[3], gi.clamp_(0, gain[2] - 1)))`
to
`indices.append((b, a, gj.clamp_(0, gain[3].to(torch.int64) - 1), gi.clamp_(0, gain[2].to(torch.int64) - 1)))`

This should fix the problem! (At least it did for me :p)
