### ISSUE TITLE
SR part error : Input and output sizes should be greater than 0, but got input (H: 16, W: 16) output (H: 0, W: 0)

### ISSUE THREAD

**Issue by syeona** [icey-zhang/SuperYOLO#25]
Here, factor = 1 and low_level_feat = [64, 64]
please help me. .

![image](https://user-images.githubusercontent.com/130537120/231372167-862df2f2-1dfc-4f38-ae8e-c9de30b8f3ba.png)

Error message : 
Exception has occurred: RuntimeError
Input and output sizes should be greater than 0, but got input (H: 16, W: 16) output (H: 0, W: 0)

File "/home/server-3/desktop/yeona/SuperYOLO-main/models/sr_decoder_noBN_noD.py", line 38, in forward
    x = F.interpolate(x, size=[i*(factor // 2) for i in low_level_feat.size()[2:]], mode='bilinear', align_corners=True)
  File "/home/server-3/desktop/yeona/SuperYOLO-main/models/deeplabedsr.py", line 60, in forward
    x_sr= self.sr_decoder(x, low_level_feat,self.factor)
  File "/home/server-3/desktop/yeona/SuperYOLO-main/models/SRyolo.py", line 243, in forward_once
    output_sr = self.model_up(y[self.l1],y[self.l2]) #在超分上加attention
  File "/home/server-3/desktop/yeona/SuperYOLO-main/models/SRyolo.py", line 190, in forward
    y,output_sr,features = self.forward_once(steam,'yolo', profile) #zjq
  File "/home/server-3/desktop/yeona/SuperYOLO-main/models/SRyolo.py", line 117, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch_steam, s, s),torch.zeros(1, ch_steam, s, s),input_mode)[0]])  # forward
  File "/home/server-3/desktop/yeona/SuperYOLO-main/train.py", line 102, in train
    model = Model(opt.cfg, input_mode = opt.input_mode ,ch_steam=opt.ch_steam,ch=opt.ch, nc=nc, anchors=hyp.get('anchors'),config=None,sr=opt.super,factor=down_factor).to(device)  # create
  File "/home/server-3/desktop/yeona/SuperYOLO-main/train.py", line 673, in <module>
    train(hyp, opt, device, tb_writer)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 16, W: 16) output (H: 0, W: 0)

**Comment by PrisonMike-Guy** [comment]
@syeona 
This has to do with the down_factor/factor parameter. Right now it is 1, but it should be 2. 

I hard coded it to 2 in line 98 from train.py

This solved it for me, I hope this solves it for you as well!

**Comment by syeona** [comment]
> @syeona This has to do with the down_factor/factor parameter. Right now it is 1, but it should be 2.
> 
> I hard coded it to 2 in line 98 from train.py
> 
> This solved it for me, I hope this solves it for you as well!


Thank you so much ! I fixed it by referring to this ! After specifying downsampling factor to 2, a dimensional error occurred, so setting EDSR factor to 4 and it returned. Have a good day :-)

**Comment by PrisonMike-Guy** [comment]
@syeona 
Awesome to hear that you managed to fix it! Thank you very much and I wish you a good day as well!

**Comment by PrisonMike-Guy** [comment]
@syeona 
Could you provide more information about your problem? Maybe I can help with the solution.
