### ISSUE TITLE
train-val size

### ISSUE THREAD

**Issue by zhangshoulong** [icey-zhang/SuperYOLO#26]
![image](https://user-images.githubusercontent.com/52525731/231692169-b7454a53-dca3-462c-bdbd-d2d6319b958e.png)
1、这个train-val size代表train跟Val的大小是一样的吗？
1、你好，您在论文中提到训练的图片分辨率是1024，而测试的时候是512，，训练的时候图片要下采样为512，那么测试的时候图片输入大小是512，经过网络，那不也是变成了原来的1/2,变成256了吗？

**Comment by zhangshoulong** [comment]
我之前用你的代码训练自己的数据集，train大小设置为640，test也设置为640，没用你的sp分支，训练的时候，发现没啥问题，但我不知道，我这个用法对不对

**Comment by zhangshoulong** [comment]
还有个问题，train-val是一样的， 也就是说我每个epoch之后，用验证集验证一下map50-95,这两个数据集的输入网络的图片大小是一样的吗

**Comment by icey-zhang** [comment]
> 我之前用你的代码训练自己的数据集，train大小设置为640，test也设置为640，没用你的sp分支，训练的时候，发现没啥问题，但我不知道，我这个用法对不对

这样设置之后跑的就不是SuperYOLO了

**Comment by icey-zhang** [comment]
> 你好，我看了你的源码，但是我的代码能力很有限
> 没有看到在哪的代码中体现出来测试的时候512的图没有经过下采样

没有downsample

**Comment by icey-zhang** [comment]
> 还有个问题，train-val是一样的， 也就是说我每个epoch之后，用验证集验证一下map50-95,这两个数据集的输入网络的图片大小是一样的吗

嗯 是的

**Comment by zhangshoulong** [comment]
> 

这样跑也是可以的是吧？我把P3,p4,p5,打开了，这样就变成了一个支持输入两种模态数据的 带有MF模块的yolov5了是吧

**Comment by PrisonMike-Guy** [comment]
> > I used your code to train my own data set, the size of the brain is set at 640, and the test is also set at 640. When you train, you find that there is no problem, but I don’t know. My usage is right.
> 
> After this setting, it’s not SuperYOLO.

Could you elaborate/explain why it is not SuperYOLO when using an image size of 640? The technique should still work also with different image size right?

**Comment by icey-zhang** [comment]
As far as I know, the size 640 is a set of the training strategy. Why should be to set the size of 640? In my experiment, the dataset of VEDAI provides the two-size dataset in 512 and 1024, so I complete my whole experiment in size of 512, and 1024 is used to complete the SuperYOLO branch. I think if you set it to 640, it is also SuperYOLO.

> > > I used your code to train my own data set, the size of the brain is set at 640, and the test is also set at 640. When you train, you find that there is no problem, but I don’t know. My usage is right.
> > 
> > 
> > After this setting, it’s not SuperYOLO.
> 
> @icey-zhang Could you elaborate/explain why it is not SuperYOLO when using an image size of 640? The technique should still work also with different image size right?
