### ISSUE TITLE
pandas._config.config.OptionError: "No such keys(s): 'mode.use_inf_as_null'"

### ISSUE THREAD

**Issue by wenyifromsichuan** [icey-zhang/SuperYOLO#27]
您好，我在运行的时候遇到了pandas._config.config.OptionError: "No such keys(s): 'mode.use_inf_as_null'"的问题，请问您使用的哪个版本的python？是否遇到过这个问题？
![image](https://user-images.githubusercontent.com/49155720/232287953-0e3645c8-3b85-4c2a-8d4b-9d2ee884073f.png)
下面是我的Python和Pandas
![image](https://user-images.githubusercontent.com/49155720/232316124-49b364e2-0b46-4c22-aa23-2acaa3e7a937.png)

**Comment by lian704** [comment]
我也是这个问题，请问有解决吗？
