### ISSUE TITLE
你好，请问运用下载的VEDAI数据集训练时提示无标签怎么解决？

### ISSUE THREAD

**Issue by IssacaLaw** [icey-zhang/SuperYOLO#28]
错误：
![image](https://user-images.githubusercontent.com/71266344/232768985-06bfa358-8787-46ab-866a-7b2977cd010d.png)
SRvedai.yaml文件：
![image](https://user-images.githubusercontent.com/71266344/232769115-06ad9699-cff8-416c-81b0-e6745e1effd0.png)
已运行transform_vedai.py文件，txt文件如下：
![image](https://user-images.githubusercontent.com/71266344/232769398-ec87b0d4-2202-4cf7-b1a0-773686ded73e.png)

**Comment by icey-zhang** [comment]
同问题 https://github.com/icey-zhang/SuperYOLO/issues/16

**Comment by sun-0704** [comment]
请问验证集和测试集的路径为什么一样呢
