### ISSUE TITLE
> 你好，我看了你的源码，但是我的代码能力很有限

### ISSUE THREAD

**Issue by zhangshoulong** [icey-zhang/SuperYOLO#29]
> 你好，我看了你的源码，但是我的代码能力很有限
> 没有看到在哪的代码中体现出来测试的时候512的图没有经过下采样

没有downsample

_Originally posted by @icey-zhang in https://github.com/icey-zhang/SuperYOLO/issues/26#issuecomment-1514634434_

**Comment by icey-zhang** [comment]
测试的时候输入是512的图片，没有下采样操作
