### ISSUE TITLE
用small_EDSR_fold1进行test报错：ModuleNotFoundError: No module named 'models.deeplabedsr'

### ISSUE THREAD

**Issue by yuan-kai-design** [icey-zhang/SuperYOLO#3]

**Comment by icey-zhang** [comment]
您好，这个问题应该不会出现，这个文件是存在的[models.deeplabedsr](https://github.com/icey-zhang/SuperYOLO/blob/main/models/deeplabedsr.py)
修改数据集路径后即可测试通过.

可考虑原因：是否代码未下载完全或者下载的代码不是最新版本？
