### ISSUE TITLE
train on visDrone

### ISSUE THREAD

**Issue by mahilaMoghadami** [icey-zhang/SuperYOLO#32]
hello
thanks for implentation sharing
it was interesting for me.

is it possible to train SUPER-YOLO on other datasets such as VisDrone?

thank you.

**Comment by icey-zhang** [comment]
It can be used in many object datasets. If the VisDrone only has one modality, you can refer to the GHOST repo which uses the NWPU dataset to conduct the SuperYOLO to the VisDrone dataset.

**Comment by mahilaMoghadami** [comment]
thank you
could you please give me GHOST repository link address?

**Comment by icey-zhang** [comment]
https://github.com/icey-zhang/GHOST
