### ISSUE TITLE
Output images showing up with inverted colors

### ISSUE THREAD

**Issue by AskSid** [icey-zhang/SuperYOLO#38]
I've noticed that while evaluating the model after finetuning on my own data, the output images in the runs/test folder are sometimes negative (inverted colors of the image inputted). This is not consistent, as an inverted image in one run will not be the same as another. I've looked through the code, but couldn't find anything that would be causing this or be using it as a processing step. Any help would be appreciated!

**Comment by icey-zhang** [comment]
I don't know what your meaning of the 'negative' is.
