### ISSUE TITLE
没找到train_up.py文件

### ISSUE THREAD

**Issue by SHR1103** [icey-zhang/SuperYOLO#4]

**Comment by Husky13S** [comment]
I didn't found it, either.  Hope the author release soon.

**Comment by zgy-886688** [comment]
没有对应的train_up.py文件，希望作者早日发布，谢谢

**Comment by turningpage-cm** [comment]
什么时候可以发布train_py文件？

**Comment by icey-zhang** [comment]
论文被接受就会公布了，希望大家不要着急
The code about train_up.py will open soon when the paper is accepted, please wait
