### ISSUE TITLE
数据集载入问题

### ISSUE THREAD

**Issue by liwenqiang2022** [icey-zhang/SuperYOLO#40]
Scaled weight_decay = 0.0005
train: Scanning 'D:\xxx\SuperYOLO-main\dataset\VEDAI_1024\images.cache' for images and labels... 0 found, 1089 missing, 0 empty, 0 corrupted: 100%|██████████| 1089/1089 [00:00<?, ?it/s]
Traceback (most recent call last):
File "D:/xxx/SuperYOLO-main/train.py", line 673, in <module>
train(hyp, opt, device, tb_writer)
File "D:/xxx/SuperYOLO-main/train.py", line 212, in train
dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
File "D:\xxx\SuperYOLO-main\utils\datasets.py", line 92, in create_dataloader_sr
dataset = LoadImagesAndLabels_sr(path, imgsz, batch_size,
File "D:\xxx\SuperYOLO-main\utils\datasets.py", line 701, in init
assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {help_url}'
AssertionError: train: No labels in D:\xxx\SuperYOLO-main\dataset\VEDAI_1024\images.cache. Can not train without labels. See https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

Process finished with exit code 1

**Comment by icey-zhang** [comment]
这是没找到数据集，你单步调试一下吧，可能是路径不对还是什么问题

**Comment by GDragon986** [comment]
> Scaled weight_decay = 0.0005 train: Scanning 'D:\xxx\SuperYOLO-main\dataset\VEDAI_1024\images.cache' for images and labels... 0 found, 1089 missing, 0 empty, 0 corrupted: 100%|██████████| 1089/1089 [00:00<?, ?it/s] Traceback (most recent call last): File "D:/xxx/SuperYOLO-main/train.py", line 673, in train(hyp, opt, device, tb_writer) File "D:/xxx/SuperYOLO-main/train.py", line 212, in train dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt, File "D:\xxx\SuperYOLO-main\utils\datasets.py", line 92, in create_dataloader_sr dataset = LoadImagesAndLabels_sr(path, imgsz, batch_size, File "D:\xxx\SuperYOLO-main\utils\datasets.py", line 701, in init assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {help_url}' AssertionError: train: No labels in D:\xxx\SuperYOLO-main\dataset\VEDAI_1024\images.cache. Can not train without labels. See https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data
> 
> Process finished with exit co
您好，请问您解决这个问题了吗？怎么解决的呀？

**Comment by icey-zhang** [comment]
路径不对，你看报错是1089 missing，说明没有读取到标签。

**Comment by ljs-1** [comment]
可以明确一下数据集到底应该什么格式方吗，您源码中给出的应该不正确

**Comment by J-Collar** [comment]
> 可以明确一下数据集到底应该什么格式方吗，您源码中给出的应该不正确

您好，请问您解决这个问题了吗
