### ISSUE TITLE
A question about the test code

### ISSUE THREAD

**Issue by LazyShark2001** [icey-zhang/SuperYOLO#42]
![A](https://github.com/icey-zhang/SuperYOLO/assets/141640045/b89af29a-83c4-45a6-bdf6-483fc7d99c1c)
When I enter this line of code, I get the following error - "python test.py --weights weights/YOLOv5s/multi/yolov5s_multi_fold1.pt --input_mode RGB+IR+MF". How should I solve this problem? There are two files in your models folder, "yolors.py" and "SRyolo.py", will these two files help my problem? Thank you and wish you a happy life

**Comment by LazyShark2001** [comment]
Thanks to the author, the problem has been resolved. The reason is that there is an error in the weight file specification.

**Comment by icey-zhang** [comment]
I am glad that you have solved the problem. If you have any other questions, you can concat us.
