### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by wxh1402714457** [icey-zhang/SuperYOLO#43]
![image](https://github.com/icey-zhang/SuperYOLO/assets/97824555/ed4995f5-a1c5-412e-9f5d-d39736f054a7)
1.混合训练的时候，train_batch01.jpg上看到，只有RGB图像，没有IR图像呀
2.单独训练IR，train_batch01.jpg上，也是RGB图像，没有IR图像，这是对的吗？还是我理解问题，我理解的是RGB和IR图像都在里面，提供更多的目标样本

**Comment by wxh1402714457** [comment]
混合训练：RGB+IR+MF，单独训练：IR
![image](https://github.com/icey-zhang/SuperYOLO/assets/97824555/cbfce7ae-e481-44be-b1d6-3453a09d06b0)
这是混合训练的图，上一张是IR训练的图，都是RGB的呀，没有红外线的图，这是啥问题？

**Comment by icey-zhang** [comment]
您好，这是因为训练的可视化的时候，用的都是RGB的图，你可以看train.py 第144行：https://github.com/icey-zhang/SuperYOLO/blob/481322d02e366e805c1457e782242ac7dbb391d5/train.py#L444
测试的时候是分开了的，你可以看test.py 第245行 https://github.com/icey-zhang/SuperYOLO/blob/481322d02e366e805c1457e782242ac7dbb391d5/test.py#L245

**Comment by wxh1402714457** [comment]
> 



> 您好，这是因为训练的可视化的时候，用的都是RGB的图，你可以看 train.py 第144行：
> 
> https://github.com/icey-zhang/SuperYOLO/blob/481322d02e366e805c1457e782242ac7dbb391d5/train.py#L444
> 
> 
> 测试的时候是分开了的，你可以看 test.py 第245行
> https://github.com/icey-zhang/SuperYOLO/blob/481322d02e366e805c1457e782242ac7dbb391d5/test.py#L245
也就是说，训练是RGB和IR一块训练的，只不过可视化是只显示了RGB图像？

**Comment by wxh1402714457** [comment]
？？？作者可以回答一下吗？麻烦您了

**Comment by icey-zhang** [comment]
多模态的时候是在RGB上做了可视化

**Comment by wxh1402714457** [comment]
为啥低分辨率的val，使用SR后效果并不好，还不如高分辨率的val
