### ISSUE TITLE
mAP comparison with YOLOv5

### ISSUE THREAD

**Issue by melika-sce** [icey-zhang/SuperYOLO#44]
Hi, and thanks for this great work.
I trained SuperYOLO with train_image_size =1024 and test_image_size=512 on VisDrone dataset and I want to compare the mAP result with YOLOv5, but I was not sure if I have to compare SuperYOLO with YOLOv5 that was trained on 512 image-size or 1024 image-size?

**Comment by icey-zhang** [comment]
We compare the SuperYOLO with **parameter** train_image_size =1024 and test_image_size=512 and the YOLOv5 trained on 512 image-size and tested 512 image-size. 

But actually, when training the SuperYOLO, the images are downsampled to 512 size and then fed into the detection network. The 1024-size image is used to train the super-resolution branch as the label.

So it is a fair comparison.

**Comment by melika-sce** [comment]
Thanks for explanation
