### ISSUE TITLE
train

### ISSUE THREAD

**Issue by shuoshuoshuoer** [icey-zhang/SuperYOLO#45]
您好，我这边在训练时，按照您的步骤先下载数据集然后transform,运行只训练RGB,还是出现标签找不到：No labels in D:\experienment\SuperYOLO-main\SuperYOLO-main\dataset\VEDAI_1024\images.cache. Can not train without labels；您知道这该如何解决么

**Comment by icey-zhang** [comment]
可以看一下断点运行到这 https://github.com/icey-zhang/SuperYOLO/blob/e6c5c726ccce88aea38760e02c13baef79e8819e/utils/datasets.py#L407，路径对不对。

**Comment by ljs-1** [comment]
没有预训练权重的化怎么样训练自己的数据集成

**Comment by Joey-He** [comment]
> 您好，我这边在训练时，按照您的步骤先下载数据集然后transform,运行只训练RGB,还是出现标签找不到：No labels in D:\experienment\SuperYOLO-main\SuperYOLO-main\dataset\VEDAI_1024\images.cache. Can not train without labels；您知道这该如何解决么

您好 您解决了吗

**Comment by dwddw** [comment]
```
def img2label_paths(img_paths):
    # Define label paths as a function of image paths
    sa = 'images'
    sb = 'labels'
    # sa, sb = os.sep + 'images' + os.sep, os.sep + 'labels' + os.sep  # /images/, /labels/ substring
    return [x.replace(sa, sb, 1).replace('_' + x.split('_')[-1], '.txt') for x in img_paths] #replace('.' + x.split('.')[-1], '.txt')
```

**Comment by Joey-He** [comment]
> ```
> def img2label_paths(img_paths):
>     # Define label paths as a function of image paths
>     sa = 'images'
>     sb = 'labels'
>     # sa, sb = os.sep + 'images' + os.sep, os.sep + 'labels' + os.sep  # /images/, /labels/ substring
>     return [x.replace(sa, sb, 1).replace('_' + x.split('_')[-1], '.txt') for x in img_paths] #replace('.' + x.split('.')[-1], '.txt')
> ```

谢谢 成功运行了

**Comment by kashinou** [comment]
こんにちは。どこをどのように変更したら解決しましたか？
具体的な手法を教えていただけると嬉しいです。

**Comment by farhaniqbalbajwa** [comment]
i am getting the same error
