### ISSUE TITLE
训练一直报错，数据集也是下载的您的，怎么回事呢

### ISSUE THREAD

**Issue by ljs-1** [icey-zhang/SuperYOLO#49]
train: Scanning 'D:\SuperYOLO-main\dataset\VEDAI_1024\images.cache' for images and labels... 0 found, 1089 missing, 0 empty, 0 corrupted: 100%|██████████| 1089/1089 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/SuperYOLO-main/train.py", line 673, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:/SuperYOLO-main/train.py", line 216, in train
    image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
  File "D:\SuperYOLO-main\utils\datasets.py", line 101, in create_dataloader_sr
    prefix=prefix)
  File "D:\SuperYOLO-main\utils\datasets.py", line 701, in __init__
    assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {help_url}'
AssertionError: train: No labels in D:\SuperYOLO-main\dataset\VEDAI_1024\images.cache. Can not train without labels. See https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

**Comment by liwenqiang2022** [comment]
You can try running the author's code under Linux

**Comment by Joey-He** [comment]
我也是这样 您解决了吗

**Comment by so-wee** [comment]
我也是这样的，请问您是如何解决的？
#

**Comment by icey-zhang** [comment]
你好，可以参考这个issue去尝试解决一下 https://github.com/icey-zhang/SuperYOLO/issues/45
