### ISSUE TITLE
文章中所提出的Pixel-level fusion具体是指什么融合方法，文章中所有的实验都是基于IR+RGB模式检测的吗

### ISSUE THREAD

**Issue by yuan-kai-design** [icey-zhang/SuperYOLO#5]

**Comment by XuedongZhu** [comment]
如果没有IR图像，只有RGB的话，怎么进行参考。这个融合方法觉得很不错，或者说我可不可以针对不同尺度的目标去进行一个融合的训练，小目标和大目标通过融合进行训练。还请作者给予指导

**Comment by XuedongZhu** [comment]
如果没有IR图像，只有RGB的话，怎么进行参考。这个融合方法觉得很不错，或者说我可不可以针对不同尺度的目标去进行一个融合的训练，小目标和大目标通过融合进行训练。还请作者给予指导

**Comment by icey-zhang** [comment]
文章中有具体提到pixel-level的融合方法，实验部分消融实验都是基于多模态（RGB+IR）完成的，TABLE VIII中RGB或者IR都是基于单一模态的，而multi指的是多模态（RGB+IR），TABLE IX 是一些在单模态（RGB）的遥感数据集上的算法验证结果。

**Comment by icey-zhang** [comment]
> 如果没有IR图像，只有RGB的话，怎么进行参考。这个融合方法觉得很不错，或者说我可不可以针对不同尺度的目标去进行一个融合的训练，小目标和大目标通过融合进行训练。还请作者给予指导

不是太能理解您的问题，还请说的详细一些，针对不同尺度的目标的融合具体指？

**Comment by XuedongZhu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我想验证一下您提出方法的效果，但是我只有RGB图像，请问IR图像可以通过将RGB转换为IR进行实验吗---- 回复的原邮件 ----
  
    
      
        
         发件人 
        
        
            zhang ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月7日 14:51
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [icey-zhang/SuperYOLO] 文章中所提出的Pixel-level fusion具体是指什么融合方法，文章中所有的实验都是基于IR+RGB模式检测的吗 (Issue #5)
        
      
    
  
  

文章中有具体提到pixel-level的融合方法，实验部分消融实验都是基于多模态（RGB+IR）完成的，TABLE VIII中RGB或者IR都是基于单一模态的，而multi指的是多模态（RGB+IR），TABLE IX 是一些在单模态（RGB）的遥感数据集上的算法验证结果。

**Comment by icey-zhang** [comment]
您好，您可以采用这个https://github.com/icey-zhang/GHOST里面的NWPU数据集的训练方式，NWPU数据集的输入是RGB图像，另外如果你的文件夹名字和NWPU有所不同的话，建议你修改文件https://github.com/icey-zhang/GHOST/blob/main/utils/datasets_single.py这个文件的数据集路径名字

**Comment by leileilei2000** [comment]
> 文章中有具体提到pixel-level的融合方法，实验部分消融实验都是基于多模态（RGB+IR）完成的，TABLE VIII中RGB或者IR都是基于单一模态的，而multi指的是多模态（RGB+IR），TABLE IX 是一些在单模态（RGB）的遥感数据集上的算法验证结果。

![Snipaste_2024-01-11_20-39-21](https://github.com/icey-zhang/SuperYOLO/assets/144891526/bc27978f-51f3-4021-a3fd-4da407d7a19e)
![Snipaste_2024-01-11_20-43-05](https://github.com/icey-zhang/SuperYOLO/assets/144891526/1f68dd20-e7b2-43e1-83c2-34d5799af117)
既然都是多模态的结果，为什么这两个表的yolov5s结果相差这么大？
