### ISSUE TITLE
迁移到yolo8出现make_anchor报错

### ISSUE THREAD

**Issue by wxh1402714457** [icey-zhang/SuperYOLO#50]
作者可以把这个模型迁移到anchor-free的yolo8上面吗？我在迁移过程中出现了make_anchor的问题：
![image](https://github.com/icey-zhang/SuperYOLO/assets/97824555/354f4b1b-04eb-4ff3-90bf-333dc208c8d3)
size只有三个参数
![image](https://github.com/icey-zhang/SuperYOLO/assets/97824555/4d1f5abe-aa93-4f6f-9d2a-fd647d70a9c8)
这是啥原因

**Comment by icey-zhang** [comment]
抱歉，对于yolov8不太了解
