### ISSUE TITLE
请问作者有没有写detect这个函数

### ISSUE THREAD

**Issue by xiaofei624** [icey-zhang/SuperYOLO#51]

**Comment by icey-zhang** [comment]
目前没有，可以参考yolov5的detect.py文件

**Comment by 4everImmortality** [comment]
但是 如果没有detect文件，论文中的检测结果图是这么出现的呢，是从exp里的batch里截图的吗？

**Comment by 4everWZ** [comment]
> 目前没有，可以参考yolov5的detect.py文件


但是 如果没有detect文件，论文中的检测结果图是这么出现的呢，是从exp里的batch里截图的吗？
