### ISSUE TITLE
 Dataset not found

### ISSUE THREAD

**Issue by Joey-He** [icey-zhang/SuperYOLO#54]
我改了transform.py里的PATH 路径 但训练的时候报了这个错误：

Traceback (most recent call last):
  File "D:\PycharmProjects\SuperYOLO\train.py", line 673, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\PycharmProjects\SuperYOLO\train.py", line 104, in train
    check_dataset(data_dict)  # check
  File "D:\PycharmProjects\SuperYOLO\utils\general.py", line 167, in check_dataset
    raise Exception('Dataset not found.')
Exception: Dataset not found.

WARNING: Dataset not found, nonexistent paths: ['D:\\home\\data\\zhangjiaqing\\dataset\\VEDAI\\fold01test_write.txt']

请问还要在哪里修改数据集的路径

**Comment by Lffhope** [comment]
请问解决了吗

**Comment by wjxxyz** [comment]
您解决问题了吗

**Comment by liwenqiang2022** [comment]
在Linux环境下不会出现此问题。

**Comment by icey-zhang** [comment]
Hello, you can refer to this issue to try to solve the https://github.com/icey-zhang/SuperYOLO/issues/45
你好，可以参考这个issue去尝试解决一下 https://github.com/icey-zhang/SuperYOLO/issues/45
