### ISSUE TITLE
local variable 'steam' referenced before assigment

### ISSUE THREAD

**Issue by wxh1402714457** [icey-zhang/SuperYOLO#56]
为啥我迁移到yolo8上会出现这个问题，在运行val.py的时候出现的，之前运行train.py也有这个问题，但是不知道怎么被我解决了，现在val.py也有这个问题，我找不到怎么解决了，作者能帮忙解答一下吗

**Comment by icey-zhang** [comment]
这个错误的意思是：没有定义这个变量之前已经使用这个变量，应该是定义顺序的不对，你再好好debug一下

**Comment by WinnieLaugh** [comment]
确实有这个报错，我用的原代码，python test.py的时候加了参数--task study就会有这个错

**Comment by WinnieLaugh** [comment]
test.py的402行，少传了一个opt.input_mode
