### ISSUE TITLE
mf

### ISSUE THREAD

**Issue by zhu011** [icey-zhang/SuperYOLO#57]
想请教一下，您网络是如何实现两种类型图片输入的，都需要label吗，dataloader是如何运作的

**Comment by icey-zhang** [comment]
您好，虽然输入两种类型图像，但是label只有一个与之对应，所以输入是dataloader是会加载三个数据，包括两张图片和一个标签

**Comment by leileilei2000** [comment]
> 您好，虽然输入两种类型图像，但是label只有一个与之对应，所以输入是dataloader是会加载三个数据，包括两张图片和一个标签

请问您的意思是，两张图片共用一个label吗
