### ISSUE TITLE
common.py中的MF

### ISSUE THREAD

**Issue by yuan-kai-design** [icey-zhang/SuperYOLO#58]
根据论文描述这部分开始应有的两个SE，但被注释了，然后应该在MF中有归一化操作，但是这里好像没有看到
![image](https://github.com/icey-zhang/SuperYOLO/assets/78480103/f7a4ae19-c0eb-4abc-b7d6-d218f5892296)

**Comment by icey-zhang** [comment]
你好，因为后续发现这两个SE block的实现结果与直接乘以0.5的系数结果是一致的，所以将代码进行了简单修改
