### ISSUE TITLE
AssertionError: train: No labels in dataset\VEDAI_1024\images.cache.

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#59]
不能训练啊

**Comment by leileilei2000** [comment]
已解决

**Comment by qiuelk12138** [comment]
兄弟是怎么解决的呀

**Comment by leileilei2000** [comment]
你可以在这里找到解决方法https://github.com/icey-zhang/SuperYOLO/issues/45




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icey-zhang/SuperYOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 晚上10:10
***@***.***&gt;;
抄送:&nbsp;" ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [icey-zhang/SuperYOLO] AssertionError: train: No labels in dataset\VEDAI_1024\images.cache. (Issue #59)





 
兄弟是怎么解决的呀
