### ISSUE TITLE
关于【特征图可视化】的问题

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#60]
请问作者是自己写的这部分代码吗，在您提供的内容中没有找到相关的代码

**Comment by icey-zhang** [comment]
可视化就是一个很简单的特征可视，[Matplotlib]库就行

**Comment by Thomas-403** [comment]
> 可视化就是一个很简单的特征可视，[Matplotlib]库就行

请问显示的是热力图吗
