### ISSUE TITLE
输出SR分支结果

### ISSUE THREAD

**Issue by Tou-ge** [icey-zhang/SuperYOLO#61]
请问怎么输出SR分支的超分后的结果图，来计算PSNR和SSIM值

**Comment by 225ceV** [comment]
我也在关注这个问题，因为我没有在代码中找到SuperResolution类的实现，但是该功能似乎在Model.model_up中实现了，我想超分辨率的结果应该在下面的代码中
https://github.com/icey-zhang/SuperYOLO/blob/fcd54aff606327ae72d352eee1a5fdb794a8b6ed/models/SRyolo.py#L187-L197
需要进行更改，在training不为True的时候时候也进行输出
希望对你有帮助@Tou-ge，另外我想知道项目构建依靠的yolov5版本是那个，是5.0，6.0？还是以前的

**Comment by icey-zhang** [comment]
1.output_sr是超分结果 2.依靠的yolov5 5.0版本
