### ISSUE TITLE
inference stage以及SR分支去除

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#65]
请问作者您的论文中提到的inference stage具体是代码的哪部分？是在哪里去除的SR分支？
还有就是SR分支在论文中好像没有输出结果，是如何影响到后续的检测的呢？

**Comment by leileilei2000** [comment]
很抱歉，对于前两个问题还是不明白，第三问题论文中提到“The SR guides the related learning of spatial dimension and transfers it to the main branch, thereby improving the performance of object detection.”但是在结构图中并没有找到是如何将learning转移到主分支的，请问您能帮我解答吗

> 请问作者您的论文中提到的inference stage具体是代码的哪部分？是在哪里去除的SR分支？ 还有就是SR分支在论文中好像没有输出结果，是如何影响到后续的检测的呢？

**Comment by icey-zhang** [comment]
通过损失函数的梯度回传，超分的损失函数和检测的损失函数会同时优化backbone部分
