### ISSUE TITLE
完全来源了吗

### ISSUE THREAD

**Issue by XuedongZhu** [icey-zhang/SuperYOLO#7]
请问代码已经完全开源了吗

**Comment by icey-zhang** [comment]
目前训练的代码还未开源，测试部分以及网络结构都是开源了的

**Comment by XuedongZhu** [comment]
我想验证一下您提出方法的效果，但是我只有RGB图像，请问IR图像可以通过将RGB转换为IR进行实验吗

**Comment by icey-zhang** [comment]
您好，您可以采用这个https://github.com/icey-zhang/GHOST 里面的NWPU数据集的训练方式，NWPU数据集的输入是RGB图像，另外如果你的文件夹名字和NWPU有所不同的话，建议你修改https://github.com/icey-zhang/GHOST/blob/main/utils/datasets_single.py 这个文件的数据集路径名字
