### ISSUE TITLE
命令行后加了【--multi-scale】报错，但是不清楚怎么改

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#70]
D:\softwares\Anaconda\envs\pytorch\Lib\site-packages\torch\nn\modules\loss.py:101: UserWarning: Using a target size (torch.Size([2, 3, 1024, 1024])) that is different to the input size (torch.Size([2, 3, 1536, 1536])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
请问这里的1536具体是修改哪个部分呢？

**Comment by icey-zhang** [comment]
没有使用这个，可能需要你自己调试了~
