### ISSUE TITLE
用tensorboard命令不显示graphs网络结构

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#71]
想要通过tensorboard进一步学习网络结构，但是并不显示graphs

**Comment by Tou-ge** [comment]
> 想要通过tensorboard进一步学习网络结构，但是并不显示graphs

您好，是否愿意加个联系方式，一起讨论一下

**Comment by leileilei2000** [comment]
> > 想要通过tensorboard进一步学习网络结构，但是并不显示graphs
> 
> 您好，是否愿意加个联系方式，一起讨论一下

非常乐意，不过我只是一个刚接触的新人，可能并没有办法解决相关的问题
