### ISSUE TITLE
将GFLOPs注释解开，前后参数输出不一样

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#76]
![Snipaste_2024-01-13_09-47-20](https://github.com/icey-zhang/SuperYOLO/assets/144891526/17e859c8-f4a5-47c8-a1d8-24b7c37aa9da)

**Comment by leileilei2000** [comment]
使用的是作者您提供的权重训练，但是结果与论文结果描述不一致

**Comment by icey-zhang** [comment]
thop这个库在使用时因为版本的不同，计算结果出来会不太一样

**Comment by icey-zhang** [comment]
参照https://github.com/icey-zhang/SuperYOLO/issues/77 的回答，感谢
