### ISSUE TITLE
为什么两个表的GFLOPs的单位不同呢，并且在测试时发现一个模型的参数输出不同？

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#77]
![Snipaste_2024-01-13_09-53-19](https://github.com/icey-zhang/SuperYOLO/assets/144891526/8d1df645-de5c-4eaa-8d6e-bee9ae6edd2d)
![Snipaste_2024-01-13_09-47-20](https://github.com/icey-zhang/SuperYOLO/assets/144891526/be367bb7-3721-41a5-827e-c14d9cf6eb51)

**Comment by icey-zhang** [comment]
您好，YOLOv5s(noFocus)是没有加MF融合模块的，所以参数量和计算量会比较少

**Comment by icey-zhang** [comment]
这个是写错了哟，上面那个表的G应该删除！感谢你的指正

**Comment by leileilei2000** [comment]
> 这个是写错了哟，上面那个表的G应该删除！感谢你的指正

谢谢您的回答！但是第二个问题还是想请教您，为什么params和GFLOPS两个的结果不一样呢，我是解开了您的注释后发现的
![Snipaste_2024-01-13_09-47-20](https://github.com/icey-zhang/SuperYOLO/assets/144891526/6092836e-c6fe-4c0c-b7c9-adafbc53add3)

**Comment by icey-zhang** [comment]
thop函数的版本问题

**Comment by icey-zhang** [comment]
![image](https://github.com/icey-zhang/SuperYOLO/assets/54712081/3f81d278-b4a7-4073-b349-d8a2d49cb249)
和论文最后的算法是一致的！！！！！！！！

我在https://github.com/icey-zhang/SuperYOLO/issues/74这个issue中已经解释了喔，表V SuperYOLO（noFocus）是没有加MF融合模块的
