### ISSUE TITLE
results.txt文件最后三列表示什么

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#78]
![results](https://github.com/icey-zhang/SuperYOLO/assets/144891526/fbee347a-3214-42ea-9936-4d669d07ae2d)
前面的每个值我都从每次打印的results中找到了与之对应的指标，但是最后3列我无法确定是什么，并且它们的值一样

**Comment by icey-zhang** [comment]
这个是yolov5自带的，我并无进行修改
