### ISSUE TITLE
多模态融合中的【Addition】

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#79]
![Snipaste_2024-01-15_18-33-43](https://github.com/icey-zhang/SuperYOLO/assets/144891526/da052905-6832-4266-9f6c-783fec0aa496)
我看了您在MF块中定义的【bottleneck】来进行【Addition】，但是我有疑问是

您是用conv2d定义的，它的输入是两组信息【Addition】后的，这里相加是在对应的维度上的每个值直接相加吗?

那之前提取到的通道特征也与原始信息对应相加，这是否会影响到所提取的通道特征信息在后续的传递？

**Comment by icey-zhang** [comment]
1.是直接相加 2.通过将通道特征与原始信息相加，我们引入了原始信息的补充，从而丰富了特征表示。
