### ISSUE TITLE
不同fold训练权重用test.py测试相差很大

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#83]
![0](https://github.com/icey-zhang/SuperYOLO/assets/144891526/9d6b2669-0601-4ae3-9e09-1b7dcdd14579)
![1](https://github.com/icey-zhang/SuperYOLO/assets/144891526/cc8b32dc-6a49-4022-a401-c2c3f99a5a9b)
使用同一fold训练后的权重测试只有67，但是不同fold权重测试却能达到94甚至更高99，但是这十fold的内容基本都是相同的不是吗？

**Comment by Tou-ge** [comment]
您好，我觉得您对此项目非常了解，可以通过15253761013@163.com发送一下联系方式吗，有些问题想请教一下

**Comment by icey-zhang** [comment]
I advise you to check the image name in different fold datasets. Training on flod1 and testing on fold1 is correct. Training fold1 and testing fold2 are wrong. Because the images in the fold1 train may be the same as the images in the fold2 test.

**Comment by leileilei2000** [comment]
您是正确的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月31日(星期三) 下午3:10
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icey-zhang/SuperYOLO] 不同fold训练权重用test.py测试相差很大 (Issue #83)





 
我建议您检查不同文件夹数据集中的图像名称。flod1上的训练和fold1上的测试是正确的。训练文件夹1和测试文件夹2是错误的。因为文件夹1序列中的图像可能与文件夹2测试中的图像相同。
 
—
直接回复这封邮件，在GitHub上查看，或者取消订阅.
你收到这封邮件是因为你写了这个帖子。Message ID: ***@***.***&gt;
