### ISSUE TITLE
测试阶段输出SR结果

### ISSUE THREAD

**Issue by Tou-ge** [icey-zhang/SuperYOLO#84]
想在test阶段输出SR分支的结果，看测试集超分后的可视化结果，应该怎么操作

**Comment by leileilei2000** [comment]
我并不确定我的回答是否正确，但是作者好像在test阶段移除了SR分支

**Comment by icey-zhang** [comment]
如果你想在测试阶段有SR输出，你可以在https://github.com/icey-zhang/SuperYOLO/blob/30c902c7e57d6b9658b7bcf09e03e4c050b8cb68/models/SRyolo.py#L248这之前加一句output_sr = self.model_up(y[self.l1],y[self.l2])，并且返回output_sr
