### ISSUE TITLE
求助【训练时无法找到标签】

### ISSUE THREAD

**Issue by sunshinewxx** [icey-zhang/SuperYOLO#89]
作者您好，训练的时候出现错误“train: No labels in dataset\VEDAI_1024\images.cache. Can not train without labels. ”。
发现train.py的“ Trainloader”模块中“from utils.datasets_single import create_dataloader”代码标黄，utils文件夹内并没有datasets_single文件。不知道哪里出现问题，期待您的回复，非常感谢！！
![屏幕截图 2024-01-23 124754](https://github.com/icey-zhang/SuperYOLO/assets/94048186/03316ea6-89a4-4415-b0b3-464ad868d484)

**Comment by leileilei2000** [comment]
我认为你可以在这里找到解决办法。https://githubfast.com/icey-zhang/SuperYOLO/issues/45

**Comment by leileilei2000** [comment]
你可以在这里找到解决办法 https://github.com/icey-zhang/SuperYOLO/issues/45
