### ISSUE TITLE
图像分辨率

### ISSUE THREAD

**Issue by bling-bling-only** [icey-zhang/SuperYOLO#9]
super-yolo训练时，输入图像分辨率是1024的吗，在transform.py文件以及提供的数据集中都看到，训练时采用1024*1024图片作为输入，512*512图片作为测试。文章中的结果也是按照这个设置展开的吗？

**Comment by icey-zhang** [comment]
训练过程是把1024的输入，但是会经过一个下采样，所以训练和测试进网络的图像分辨率都是保持一致的，即512大小

**Comment by JusticeLin** [comment]
> 训练过程是把1024的输入，但是会经过一个下采样，所以训练和测试进网络的图像分辨率都是保持一致的，即512大小

请问这个1024下采样成512，是仅仅针对加入--super参数来执行的吗，如果我就是普通的训练，输入也为1024，但不指定超分分支参与，是不是就不会下采样了
