### ISSUE TITLE
运行SRyolo.py报错

### ISSUE THREAD

**Issue by love-whut** [icey-zhang/SuperYOLO#92]
您好作者，运行`SRyolo.py`时报错：
`IndexError: index 1 is out of bounds for dimension 0 with size 1`
请问下该怎么解决呢？

**Comment by leileilei2000** [comment]
请问您解决了吗，我有相同的问题

**Comment by Sparkle-knight** [comment]
请问您找到原因了吗，我也遇到相似的问题了
