### ISSUE TITLE
在fold1上复现不出您论文中的理论精度？

### ISSUE THREAD

**Issue by Valmet953** [icey-zhang/SuperYOLO#94]
您好，我用您的默认指令和代码复现过几次，在VEDAI数据集的fold1中，map50指标最高仅为0.78，远不及您论文中的80.9......请问您后续程序是有改进？还是有其他拓展指令？

**Comment by farhaniqbalbajwa** [comment]
Same issue. i got 78.38

**Comment by leileilei2000** [comment]
我也是，我只达到了80.74

**Comment by icey-zhang** [comment]
I think different devices running the same code will have different results. Your results are different.

**Comment by RRunTian** [comment]
训练的时候是只加载folder1是吗，我看有十个folder

**Comment by Cyeden** [comment]
> 训练的时候是只加载folder1是吗，我看有十个folder

您好！我也想问这个问题，请问你现在找到答案了么？
