### ISSUE TITLE
关于训练和测试分辨率的问题

### ISSUE THREAD

**Issue by JusticeLin** [icey-zhang/SuperYOLO#95]
您好！您的代码我最近正在复现，有点疑问需要您解答一下，是关于分辨率的问题。
在对比实验中有“训练图像-测试图像”的分辨率设置，对于其中“**训练输入图像为1024*1024，测试图像为1024部分**”有些疑问，在train.py中train_img_size理所应当设置为1024，因为根据yaml配置文件，读取的fold01_write.txt指向VEDAI1024的路径，但fold01test_write.txt指向的测试集和验证集均来自低分辨率的VEDAI，我的疑问是：
（1）在进行这样的训练时，是不是直接将test_img_size设置为1024就可以了呢，或者说需要在设置test_img_size的同时，将fold01test_write.txt指向的测试数据更改为VEDAI1024下的图片路径呢，但这样一来，对应的label文件不就需要改变吗？
（2）我看训练集和测试集虽然都来自不同的分辨率，但是VEDAI1024和VEDAI下的labels的标注信息是一样的，既然分辨率不同，它们的标注不应该不一样吗，是不是在代码中有对应不同输入尺寸进行label标注缩放的处理呢？
以上是我的疑问，因为本人刚接触目标检测不久，对许多概念比较模糊，如有冒犯之处，烦请原谅。

**Comment by icey-zhang** [comment]
label文件里面目标的location是相对位置，与图片大小无关的
