### ISSUE TITLE
我的数据集中报错显示有您的名字等路径信息

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/SuperYOLO#97]
我按照VEDAI的txt格式创建了自己的数据集以及txt，其中每一行都是dataset/train/images/0000xxx
但是报错的内容中会在前面加“\home\data\zhangjiaqing\dataset\...”等
报错显示：RuntimeError: Parent directory \home\data\zhangjiaqing\dataset\VEDAI\labels\dataset\DroneVehicle\train does not exist.

请问有解决方法吗？我也正在努力解决这个问题中

**Comment by leileilei2000** [comment]
在我不断修改之后，没有上面报错了，但是提示直接找不到图片，下图是yaml文件和报错信息
![CCC](https://github.com/icey-zhang/SuperYOLO/assets/144891526/a801da4c-9ff0-412f-8088-2a0304f9d378)

**Comment by leileilei2000** [comment]
我在train.py的对应位置加入了我的数据集名称，
报错内容是：AssertionError: train: No labels in dataset\DroneVehicle\train\labels.cache.
![ddd](https://github.com/icey-zhang/SuperYOLO/assets/144891526/f09e1146-bcfc-4af1-b74e-dfe71c115be1)
![QQ截图20240319164039](https://github.com/icey-zhang/SuperYOLO/assets/144891526/42e7eb8c-809f-4735-a3f0-084699dd731e)
正在想办法解决...

**Comment by leileilei2000** [comment]
已解决训练个人数据集问题。

**Comment by Czeni1** [comment]
> 已解决训练个人数据集问题。

请问您是怎么训练DroneVehicle数据集的呀？
