### ISSUE TITLE
why it can't find my  images and labels

### ISSUE THREAD

**Issue by 1250826219** [icey-zhang/SuperYOLO#99]
![image](https://github.com/icey-zhang/SuperYOLO/assets/110388904/92b385b0-2024-4479-8e79-2a260f92a536)

**Comment by lilero** [comment]
同问

**Comment by ljc45240526** [comment]
解决了吗

**Comment by jacksonwu09** [comment]
> [ljc45240526](/ljc45240526)

你解决了吗

**Comment by jacksonwu09** [comment]
> 同问

你解决了吗

**Comment by 573820232** [comment]
> > 同问
> 
> 你解决了吗

请问你解决了嘛

**Comment by 573820232** [comment]
> ![image](https://private-user-images.githubusercontent.com/110388904/316219313-92b385b0-2024-4479-8e79-2a260f92a536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzgyMjQsIm5iZiI6MTcxNjk3NzkyNCwicGF0aCI6Ii8xMTAzODg5MDQvMzE2MjE5MzEzLTkyYjM4NWIwLTIwMjQtNDQ3OS04ZTc5LTJhMjYwZjkyYTUzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxMDE4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGNhODYwNmVkNjM1ZDgyN2ZhNjAwYTU2MTY1MzU4N2MzNDU1NmUyM2RkYjQyOGFlNWE4YTQxNWZlMGYyYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TW70q8dadUnhg0jOsHJyyztBJbmXlOIZmIj3B3Xo8HA)

请问你解决了吗

**Comment by icey-zhang** [comment]
https://github.com/icey-zhang/SuperYOLO/issues/16
